<?php

namespace App\Http\Controllers\Auth;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AdminLogincontroller extends Controller
{
public function __call($method, $parameters)
{
    parent::__call($method, $parameters); // TODO: Change the autogenerated stub
}
}